# Generated by Django 3.2 on 2025-04-18 11:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Строка должна быть в формате "01.03.02".', regex='^\\d{2}\\.\\d{2}\\.\\d{2}$')])),
                ('speciality', models.TextField()),
                ('profs', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.level', verbose_name='Уровень подготовки')),
            ],
        ),
    ]
