# Generated by Django 3.2 on 2025-04-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('-period',)},
        ),
        migrations.AddField(
            model_name='level',
            name='period',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
